// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cerivzoqkowsfodedmev.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNlcml2em9xa293c2ZvZGVkbWV2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NDU5NjYsImV4cCI6MjA2NTUyMTk2Nn0.ZVjezP3tX6Crfca_ZyoautxeJ9DucSNiRyMhPomCg6k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);